### ISSUE TITLE
Strange imputationInfo scores

### ISSUE THREAD

**Issue by bgorm** [saigegit/SAIGE#39]
I am getting an unusual distribution of Info scores when running step2 using BGEN files. Basically 90%+ of Info scores provided in the sumstats are > 1 and only a tiny fraction are in the range that are typically filtered out. However, the association results are reasonable, so the BGEN files should be fine. Moreover, when I use the same BGENs in tools such as REGENIE or BOLT-LMM I get the expected distribution of info scores. I am working with a large heterogeneous cohort, and most of the time I am analyzing a subset of the samples in the BGENs, if that affects anything. Thanks.

**Comment by saigegit** [comment]
Hi Bryan, 

Thanks a lot for reporting this issue! This is quite important.  It has been fixed in the current version 1.1.3.  

Thanks,
Wei

**Comment by bgorm** [comment]
Thank you Wei!

I have pulled your latest container (1.1.3). However, I now encounter a couple new bugs that did not come up in the previous version. In step1 I now get the following error:
```
Error in fitNULLGLMM(plinkFile = opt$plinkFile, bedFile = opt$bedFile,  :
  unused argument (outputSepbyChr = opt$isOutputSepbyChr)
```
If I use the step1 output from a previous version of SAIGE (1.1.2), then I get the following error in step2:
```
Error in gzfile(file, "wb") : cannot open the connection
Calls: SPAGMMATtest -> ReadModel -> save -> gzfile
In addition: Warning message:
In gzfile(file, "wb") :
  cannot open compressed file '/net/hunt/zhowei/project/imbalancedCaseCtrlMixedModel/Rpackage_SPAGMMAT/SAIGE_newgit/SAIGE_1.1.0/SAIGE/extdata/obj_cc.rda', probable reason 'No such file or directory'
```
Thanks,
Bryan

**Comment by saigegit** [comment]
Hi Bryan, 

Thanks so much for the quick feedback!  Sorry for the confusion. 1.1.3 has been just updated again and the second error should has been fixed. The first error: 


Error in fitNULLGLMM(plinkFile = opt$plinkFile, bedFile = opt$bedFile,  :
  unused argument (outputSepbyChr = opt$isOutputSepbyChr)


could be because the SAIGE version called in the job is not 1.1.3 and the option outputSepbyChr is a new one added in 1.1.3. We have updated the [wrapper script ](https://github.com/saigegit/SAIGE/blob/main/extdata/step1_fitNULLGLMM.R)

Can you please try run the following script to see if the error persists? 

`docker run wzhou88/saige:1.1.3 step1_fitNULLGLMM.R --help`

Thanks,
Wei

**Comment by bgorm** [comment]
Hi Wei,

I can print the help output using your command, but I still get the error when running a step1 job. I have attached the full log for your reference.

Thanks,
Bryan

[step1.log](https://github.com/saigegit/SAIGE/files/9078008/step1.log)

**Comment by saigegit** [comment]
Hi Bryan, 

Thanks!! The error is because the option name in the step 1 wrapper script was not correctly updated. Now it should have been fixed. 

Thanks, 
Wei

**Comment by bgorm** [comment]
INFO scores now appear to be consistent with other tools, and the updated 1.1.3 version is working, so I am closing this ticket. Thanks Wei!!!
